stages:
  - build
  - docker-push

build:
  stage: build
  script:
    - mkdir build
    - echo gitlab ci > build/dummy

  artifacts:
    paths:
      - build/

docker-push:
  stage: docker-push
  image: docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies: []
  script:
    # - cat build/dummy
    - docker build -t $DOCKER_USER/express-gitlab -f Dockerfile.gitlab .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_USER/express-gitlab