stages:
  - plan
  - apply
  - docker-push
  - deploy

# default:


# init:
#   stage: .pre
#   script:

variables:
  TF_ROOT: "terraform"

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  entrypoint: [""]

before_script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=$TF_STATE_S3_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
  

plan:
  stage: plan
  script:
    - mkdir build
    - terraform plan

  artifacts:
    paths:
      - build/
  allow_failure: false

apply:
  stage: apply
  script:
    - terraform destroy -auto-approve
    
docker-build-push:
  stage: docker-push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: ""
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never
  dependencies: []

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

  script:
    # - cat build/dummy
    - docker build -t $DOCKER_USER/express-gitlab -f Dockerfile.gitlab .
    - docker push $DOCKER_USER/express-gitlab

deploy-to-ec2:
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never # working but disabled for now
  image: alpine
  stage: deploy
  script:
    - chmod +x ssh-install-deploy.sh
    - ./ssh-install-deploy.sh