stages:
  - plan
  - apply
  - docker-push
  - deploy
      


variables:
  TF_ROOT: "terraform"

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  entrypoint: [""]

.cd_root_and_init:
  before_script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=$TF_STATE_S3_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
  
plan:
  stage: plan
  rules:
    - when: never # working but disabled
  extends:
    - .cd_root_and_init
  script:
    - mkdir build
    - terraform plan

  artifacts:
    paths:
      - build/
  allow_failure: false


apply:
  stage: apply
  rules:
    # - when: never # working but disabled
  extends:
    - .cd_root_and_init
  script:
    - terraform apply-auto-approve # -destroy 
    # update GH settings env var with the new IP
    - EC2_PUBLIC_IP=$(terraform output -raw zeelz_db_ec2_ip)
    - |
      curl -X PUT \
        --form "value=$EC2_PUBLIC_IP" \
        --header "PRIVATE_TOKEN=$GITLAB_TOKEN" \
        "https://gitlab.com/api/v4/projects/75392331/variables/ZEELZ_EC2_IP"

    
docker-build-push:
  stage: docker-push
  image: docker:24
  services:
    - docker:24-dind
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # - when: never
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: ""
  dependencies: []

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

  script:
    # - cat build/dummy
    - docker build -t $DOCKER_USER/express-gitlab -f Dockerfile.gitlab .
    - docker push $DOCKER_USER/express-gitlab

deploy-to-ec2:
  image: alpine
  stage: deploy
  needs: [apply]
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # - when: never # working but disabled for now
  script:
    - chmod +x ssh-install-deploy.sh
    - ./ssh-install-deploy.sh
