stages:
  - build
  - docker-push

# build:
#   stage: build
#   script:
#     - mkdir build
#     - echo gitlab ci > build/dummy

#   artifacts:
#     paths:
#       - build/

docker-push:
  stage: docker-push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: ""
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies: []

  # before_script:
  #   - docker login --username "$DOCKER_USER" -p "$DOCKER_PASSWORD"

  script:
    # - cat build/dummy
    - echo "DOCKER_USER = '$DOCKER_USER'"
    - echo "Password length = ${#DOCKER_PASSWORD}"
    # - docker build -t $DOCKER_USER/express-gitlab -f Dockerfile.gitlab .
    # - docker push $DOCKER_USER/express-gitlab