version = 0.1
[default.deploy.parameters]
stack_name = "express-sammed-stack"
resolve_s3 = true
s3_prefix = "express-sammed-stack"
region = "us-east-1"
profile = "zeelz"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
